
package rmi.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Warehouse", targetNamespace = "http://rmi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Warehouse {


    /**
     * 
     * @param description
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrice", targetNamespace = "http://rmi/", className = "rmi.server.GetPrice")
    @ResponseWrapper(localName = "getPriceResponse", targetNamespace = "http://rmi/", className = "rmi.server.GetPriceResponse")
    public double getPrice(
        @WebParam(name = "description", targetNamespace = "")
        String description);

}
